CREATE DATABASE ProOdezhda;
GO
USE ProOdezhda;
GO



/******************************************************************************/
/***                                Table                                   ***/
/******************************************************************************/
CREATE TABLE RATING (
	RATING_ID INT IDENTITY PRIMARY KEY,
	FK_COUNTERPARTY_ID INT NOT NULL,
	RATING FLOAT NOT NULL,
	[DATE] DATE NOT NULL
);

CREATE TABLE CATEGORY_C (
	CATEGORY_C_ID INT IDENTITY PRIMARY KEY,
	[NAME] NVARCHAR(150) NOT NULL
);

CREATE TABLE COUNTERPARTY (
	COUNTERPARTY_ID INT IDENTITY PRIMARY KEY,
	[NAME] NVARCHAR(150) NOT NULL,
	FK_TYPE_ID INT NOT NULL,
	[ADDRESS] NVARCHAR(MAX) NOT NULL,
	INN VARCHAR(12) NOT NULL,
	KPP VARCHAR(9) NOT NULL,
	OGRN VARCHAR(13) NOT NULL,
	DIRECTOR NVARCHAR(150) NOT NULL,
	TELEPHONE NVARCHAR(18) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	FK_CATEGORY_C_ID INT
);

CREATE TABLE [TYPE] (
	[TYPE_ID] INT IDENTITY PRIMARY KEY,
	[NAME] NVARCHAR(150) NOT NULL,
	SHORT_NAME NVARCHAR(15) NOT NULL
);

CREATE TABLE DISPATCH (
	DISPATCH_ID INT IDENTITY PRIMARY KEY,
	FK_REQUEST_ID INT NOT NULL,
	[DATE] DATE NOT NULL,
	FK_USER_ID INT NOT NULL
);

CREATE TABLE REQUEST (
	REQUEST_ID INT IDENTITY PRIMARY KEY,
	FK_COUNTERPARTY_ID INT NOT NULL,
	[DATE] DATE NOT NULL,
	CUTOFF_DATE DATE NOT NULL
);
CREATE TABLE REQUEST_LIST (
	REQUEST_LIST_ID INT IDENTITY PRIMARY KEY,
	FK_REQUEST_ID INT NOT NULL,
	FK_NOMENCLATURE_ID INT NOT NULL,
	QUANTITY FLOAT NOT NULL,
	PRICE MONEY NOT NULL,
	[SUM] MONEY NOT NULL
);

CREATE TABLE RETAIL_REPORT (
	RETAIL_REPORT_ID INT IDENTITY PRIMARY KEY,
	FK_COUNTERPARTY_ID INT NOT NULL,
	[DATE] DATE NOT NULL
);
CREATE TABLE RETAIL_REPORT_LIST (
	RETAIL_REPORT_LIST_ID INT IDENTITY PRIMARY KEY,
	FK_RETAIL_REPORT_ID INT NOT NULL,
	FK_NOMENCLATURE_ID INT NOT NULL,
	QUANTITY FLOAT NOT NULL,
	PRICE MONEY NOT NULL,
	[SUM] MONEY NOT NULL
);

CREATE TABLE PURCHASE_INVOICE (
	PURCHASE_INVOICE_ID INT IDENTITY PRIMARY KEY,
	FK_ORDER_ID INT NOT NULL,
	[DATE] DATE NOT NULL
);

CREATE TABLE [ORDER] (
	ORDER_ID INT IDENTITY PRIMARY KEY,
	FK_COUNTERPARTY_ID INT NOT NULL,
	[DATE] DATE NOT NULL,
	CUTOFF_DATE DATE NOT NULL,
	FK_USER_ID INT NOT NULL
);
CREATE TABLE ORDER_LIST (
	ORDER_LIST_ID INT IDENTITY PRIMARY KEY,
	FK_ORDER_ID INT NOT NULL,
	FK_NOMENCLATURE_ID INT NOT NULL,
	QUANTITY FLOAT NOT NULL,
	PRICE MONEY NOT NULL,
	[SUM] MONEY NOT NULL
);

CREATE TABLE NOMENCLATURE (
	NOMENCLATURE_ID INT IDENTITY PRIMARY KEY,
	[NAME] NVARCHAR(150) NOT NULL,
	FK_CATEGORY_N_ID INT
);

CREATE TABLE CATEGORY_N (
	CATEGORY_N_ID INT IDENTITY PRIMARY KEY,
	[NAME] NVARCHAR(150) NOT NULL
);

CREATE TABLE [USER] (
	[USER_ID] INT IDENTITY PRIMARY KEY,
	[LOGIN] NVARCHAR(150) NOT NULL,
	[PASSWORD] VARCHAR(25) NOT NULL,
	FK_POSITION_ID INT NOT NULL
);

CREATE TABLE USER_ACTIVITY (
	USER_ACTIVITY_ID INT IDENTITY PRIMARY KEY,
	FK_USER_ID INT NOT NULL,
	ENTRY_TIME DATETIME NOT NULL,
	EXIT_TIME DATETIME NOT NULL
);

CREATE TABLE POSITION (
	POSITION_ID INT IDENTITY PRIMARY KEY,
	[NAME] NVARCHAR(150) NOT NULL
);
GO



/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE RATING ADD FOREIGN KEY (FK_COUNTERPARTY_ID) REFERENCES COUNTERPARTY (COUNTERPARTY_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;


ALTER TABLE COUNTERPARTY ADD FOREIGN KEY (FK_TYPE_ID) REFERENCES [TYPE] ([TYPE_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE COUNTERPARTY ADD FOREIGN KEY (FK_CATEGORY_C_ID) REFERENCES CATEGORY_C (CATEGORY_C_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;


ALTER TABLE DISPATCH ADD FOREIGN KEY (FK_REQUEST_ID) REFERENCES REQUEST (REQUEST_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE DISPATCH ADD FOREIGN KEY (FK_USER_ID) REFERENCES [USER] ([USER_ID]) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE REQUEST ADD FOREIGN KEY (FK_COUNTERPARTY_ID) REFERENCES COUNTERPARTY (COUNTERPARTY_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE REQUEST_LIST ADD FOREIGN KEY (FK_REQUEST_ID) REFERENCES REQUEST (REQUEST_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE REQUEST_LIST ADD FOREIGN KEY (FK_NOMENCLATURE_ID) REFERENCES NOMENCLATURE (NOMENCLATURE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;


ALTER TABLE RETAIL_REPORT ADD FOREIGN KEY (FK_COUNTERPARTY_ID) REFERENCES COUNTERPARTY (COUNTERPARTY_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE RETAIL_REPORT_LIST ADD FOREIGN KEY (FK_RETAIL_REPORT_ID) REFERENCES RETAIL_REPORT (RETAIL_REPORT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE RETAIL_REPORT_LIST ADD FOREIGN KEY (FK_NOMENCLATURE_ID) REFERENCES NOMENCLATURE (NOMENCLATURE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;


ALTER TABLE PURCHASE_INVOICE ADD FOREIGN KEY (FK_ORDER_ID) REFERENCES [ORDER] (ORDER_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE [ORDER] ADD FOREIGN KEY (FK_COUNTERPARTY_ID) REFERENCES COUNTERPARTY (COUNTERPARTY_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE [ORDER] ADD FOREIGN KEY (FK_USER_ID) REFERENCES [USER] (USER_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE ORDER_LIST ADD FOREIGN KEY (FK_ORDER_ID) REFERENCES [ORDER] (ORDER_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE ORDER_LIST ADD FOREIGN KEY (FK_NOMENCLATURE_ID) REFERENCES NOMENCLATURE (NOMENCLATURE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;


ALTER TABLE NOMENCLATURE ADD FOREIGN KEY (FK_CATEGORY_N_ID) REFERENCES CATEGORY_N (CATEGORY_N_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE [USER] ADD FOREIGN KEY (FK_POSITION_ID) REFERENCES POSITION (POSITION_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE USER_ACTIVITY ADD FOREIGN KEY (FK_USER_ID) REFERENCES [USER] (USER_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
GO


/******************************************************************************/
/***                         Insert into table                              ***/
/******************************************************************************/

INSERT INTO [TYPE] ([NAME], SHORT_NAME) VALUES (N'Общество с ограниченной ответственностью', N'ООО');
INSERT INTO [TYPE] ([NAME], SHORT_NAME) VALUES (N'Индивидуальный предприниматель', N'ИП');
INSERT INTO [TYPE] ([NAME], SHORT_NAME) VALUES (N'Акционерное общество', N'ОА');
GO

INSERT INTO [CATEGORY_C] ([NAME]) VALUES (N'Агент');
INSERT INTO [CATEGORY_C] ([NAME]) VALUES (N'Поставщик');
GO

INSERT INTO [CATEGORY_N] ([NAME]) VALUES (N'Материал');
INSERT INTO [CATEGORY_N] ([NAME]) VALUES (N'Продукция');
GO


INSERT INTO [NOMENCLATURE] ([NAME], [FK_CATEGORY_N_ID]) VALUES (N'Красная ткань', 1);
INSERT INTO [NOMENCLATURE] ([NAME], [FK_CATEGORY_N_ID]) VALUES (N'Красные нитки', 1);
INSERT INTO [NOMENCLATURE] ([NAME], [FK_CATEGORY_N_ID]) VALUES (N'Белая ткань', 1);
INSERT INTO [NOMENCLATURE] ([NAME], [FK_CATEGORY_N_ID]) VALUES (N'Белые нитки', 1);
INSERT INTO [NOMENCLATURE] ([NAME], [FK_CATEGORY_N_ID]) VALUES (N'Чёрная ткань', 1);
GO

INSERT INTO [NOMENCLATURE] ([NAME], [FK_CATEGORY_N_ID]) VALUES (N'Красное платье', 2);
INSERT INTO [NOMENCLATURE] ([NAME], [FK_CATEGORY_N_ID]) VALUES (N'Белое платье', 2);
INSERT INTO [NOMENCLATURE] ([NAME], [FK_CATEGORY_N_ID]) VALUES (N'Чёрно-красная футболка', 2);
INSERT INTO [NOMENCLATURE] ([NAME], [FK_CATEGORY_N_ID]) VALUES (N'Серые брюки', 2);
INSERT INTO [NOMENCLATURE] ([NAME], [FK_CATEGORY_N_ID]) VALUES (N'Белая рубашка', 2);
GO

INSERT INTO [POSITION] ([NAME]) VALUES (N'Менеджер');
INSERT INTO [POSITION] ([NAME]) VALUES (N'Дизайнер');
INSERT INTO [POSITION] ([NAME]) VALUES (N'Бухгалтер');
GO

INSERT INTO [USER] ([LOGIN], [PASSWORD], [FK_POSITION_ID]) VALUES (N'Менеджер', '692', 1);
GO