//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProOdezhda
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNTERPARTY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COUNTERPARTY()
        {
            this.ORDERs = new HashSet<ORDER>();
            this.RATINGs = new HashSet<RATING>();
            this.REQUESTs = new HashSet<REQUEST>();
            this.RETAIL_REPORT = new HashSet<RETAIL_REPORT>();
        }
    
        public int COUNTERPARTY_ID { get; set; }
        public string NAME { get; set; }
        public int FK_TYPE_ID { get; set; }
        public string ADDRESS { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string OGRN { get; set; }
        public string DIRECTOR { get; set; }
        public string TELEPHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> FK_CATEGORY_C_ID { get; set; }
    
        public virtual CATEGORY_C CATEGORY_C { get; set; }
        public virtual TYPE TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATING> RATINGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUEST> REQUESTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETAIL_REPORT> RETAIL_REPORT { get; set; }
    }
}
