//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProOdezhda
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISPATCH
    {
        public int DISPATCH_ID { get; set; }
        public int FK_REQUEST_ID { get; set; }
        public System.DateTime DATE { get; set; }
        public int FK_USER_ID { get; set; }
    
        public virtual REQUEST REQUEST { get; set; }
        public virtual USER USER { get; set; }
    }
}
