//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProOdezhda
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProOdezhdaEntities : DbContext
    {
        public ProOdezhdaEntities()
            : base("name=ProOdezhdaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORY_C> CATEGORY_C { get; set; }
        public virtual DbSet<CATEGORY_N> CATEGORY_N { get; set; }
        public virtual DbSet<COUNTERPARTY> COUNTERPARTies { get; set; }
        public virtual DbSet<DISPATCH> DISPATCHes { get; set; }
        public virtual DbSet<NOMENCLATURE> NOMENCLATUREs { get; set; }
        public virtual DbSet<ORDER> ORDERs { get; set; }
        public virtual DbSet<ORDER_LIST> ORDER_LIST { get; set; }
        public virtual DbSet<POSITION> POSITIONs { get; set; }
        public virtual DbSet<PURCHASE_INVOICE> PURCHASE_INVOICE { get; set; }
        public virtual DbSet<RATING> RATINGs { get; set; }
        public virtual DbSet<REQUEST> REQUESTs { get; set; }
        public virtual DbSet<REQUEST_LIST> REQUEST_LIST { get; set; }
        public virtual DbSet<RETAIL_REPORT> RETAIL_REPORT { get; set; }
        public virtual DbSet<RETAIL_REPORT_LIST> RETAIL_REPORT_LIST { get; set; }
        public virtual DbSet<TYPE> TYPEs { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<USER_ACTIVITY> USER_ACTIVITY { get; set; }
    }
}
