//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProOdezhda
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOMENCLATURE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NOMENCLATURE()
        {
            this.ORDER_LIST = new HashSet<ORDER_LIST>();
            this.REQUEST_LIST = new HashSet<REQUEST_LIST>();
            this.RETAIL_REPORT_LIST = new HashSet<RETAIL_REPORT_LIST>();
        }
    
        public int NOMENCLATURE_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> FK_CATEGORY_N_ID { get; set; }
    
        public virtual CATEGORY_N CATEGORY_N { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_LIST> ORDER_LIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUEST_LIST> REQUEST_LIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETAIL_REPORT_LIST> RETAIL_REPORT_LIST { get; set; }
    }
}
