//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProOdezhda
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER()
        {
            this.ORDER_LIST = new HashSet<ORDER_LIST>();
            this.PURCHASE_INVOICE = new HashSet<PURCHASE_INVOICE>();
        }
    
        public int ORDER_ID { get; set; }
        public int FK_COUNTERPARTY_ID { get; set; }
        public System.DateTime DATE { get; set; }
        public System.DateTime CUTOFF_DATE { get; set; }
        public int FK_USER_ID { get; set; }
    
        public virtual COUNTERPARTY COUNTERPARTY { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_LIST> ORDER_LIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASE_INVOICE> PURCHASE_INVOICE { get; set; }
    }
}
