//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProOdezhda
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURCHASE_INVOICE
    {
        public int PURCHASE_INVOICE_ID { get; set; }
        public int FK_ORDER_ID { get; set; }
        public System.DateTime DATE { get; set; }
    
        public virtual ORDER ORDER { get; set; }
    }
}
