//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProOdezhda
{
    using System;
    using System.Collections.Generic;
    
    public partial class RATING
    {
        public int RATING_ID { get; set; }
        public int FK_COUNTERPARTY_ID { get; set; }
        public double RATING1 { get; set; }
        public System.DateTime DATE { get; set; }
    
        public virtual COUNTERPARTY COUNTERPARTY { get; set; }
    }
}
