//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProOdezhda
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUEST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REQUEST()
        {
            this.DISPATCHes = new HashSet<DISPATCH>();
            this.REQUEST_LIST = new HashSet<REQUEST_LIST>();
        }
    
        public int REQUEST_ID { get; set; }
        public int FK_COUNTERPARTY_ID { get; set; }
        public System.DateTime DATE { get; set; }
        public System.DateTime CUTOFF_DATE { get; set; }
    
        public virtual COUNTERPARTY COUNTERPARTY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISPATCH> DISPATCHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUEST_LIST> REQUEST_LIST { get; set; }
    }
}
