//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProOdezhda
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUEST_LIST
    {
        public int REQUEST_LIST_ID { get; set; }
        public int FK_REQUEST_ID { get; set; }
        public int FK_NOMENCLATURE_ID { get; set; }
        public double QUANTITY { get; set; }
        public decimal PRICE { get; set; }
        public decimal SUM { get; set; }
    
        public virtual NOMENCLATURE NOMENCLATURE { get; set; }
        public virtual REQUEST REQUEST { get; set; }
    }
}
