//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProOdezhda
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETAIL_REPORT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RETAIL_REPORT()
        {
            this.RETAIL_REPORT_LIST = new HashSet<RETAIL_REPORT_LIST>();
        }
    
        public int RETAIL_REPORT_ID { get; set; }
        public int FK_COUNTERPARTY_ID { get; set; }
        public System.DateTime DATE { get; set; }
    
        public virtual COUNTERPARTY COUNTERPARTY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETAIL_REPORT_LIST> RETAIL_REPORT_LIST { get; set; }
    }
}
