//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProOdezhda
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ACTIVITY
    {
        public int USER_ACTIVITY_ID { get; set; }
        public int FK_USER_ID { get; set; }
        public System.DateTime ENTRY_TIME { get; set; }
        public System.DateTime EXIT_TIME { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
